name: sentiment-analysis-drug-reviews-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - plotly
  - nbformat
  - pytorch
  - matplotlib
  - numpy
  - seaborn
  - scikit-learn
  - scipy
  - joblib
  - imbalanced-learn=0.12.4
  # - imblearn
  - pip
  - pip:
      - datetime